### ISSUE TITLE
List index out of range when running send_group

### ISSUE THREAD

**Issue by Joemarc** [bousmahafaycal/facebook_growth#1]
Hello ! 

When i run `python3 main.py send_group`i got the error 
```File "/Users/joemarc/Desktop/facebook_growth/fb_group.py", line 22, in get_ids__list
    user_id = row[1]
IndexError: list index out of range```

The csv need to be on one single line ?

**Comment by bousmahafaycal** [comment]
Hello!  
Can show me how your CSV file looks like ?

Thanks !

**Comment by Joemarc** [comment]
Hello 
It looks like this, i've done it without the coma and tried only with the ID, unsunccessfully ! 
![capture d ecran 2018-09-04 a 18 41 40](https://user-images.githubusercontent.com/16984937/45041945-35318c00-b072-11e8-8eae-c6a6c7175b3d.png)

Thanks for your answer :)

**Comment by Angelio** [comment]
Salut, 

J'ai le même souci. voici le pb

`Traceback (most recent call last):
  File "main.py", line 47, in <module>
    send_group(fbc.client, message)
  File "main.py", line 25, in send_group
    friends = fbg.get_ids__list(csv)
  File "/Users/AC/Code/facebook_growth/fb_group.py", line 22, in get_ids__list
    user_id = row[1]
IndexError: list index out of range`

J'essaie avec deux lignes sortis en csv https://docs.google.com/spreadsheets/d/1NncijlcPGkJ5ZVEJwLNUMqZTRPLXTosXqF9cs1IPgck/edit?usp=sharing

Merci de ton aide et super ton code.
PS : attention dans medium F2— Envoyer un message automatiquement à toutes les personnes d’un groupe Facebook. tu as mis  python main.py send_friends au lieu de python main.py send_group

**Comment by bousmahafaycal** [comment]
Hello @Joemarc ,

Thanks, for your CSV file. The problem is from the tuto that doesn't give the right csv file. So, we're updating the article  to generate the good CSV file with Scraper. After that, you will be able to use facebook_growth tool correctly ! I will comment here when the article is updated. 

Thanks for your answer and sorry for the inconvenience :)

**Comment by bousmahafaycal** [comment]
Salut @Angelio ,

Effectivement, il y a un petit soucis sur le tuto qui fait que le fichier CSV n'est pas celui que facebook_growth attend en entrée. On modifie l'article très vite afin de pouvoir génerer le bon fichier. Je commenterai ici dès que l'article sera mis à jour.

Content que ça te plaise ! Je vais ajouter des fonctionnalités dès que j'aurais un peu plus de temps. 

PS : Bien vu pour la coquille, on modifie ça très vite.

**Comment by Joemarc** [comment]
Hello @bousmahafaycal , ça marche je me disais bien que c'était plus du côté du fichier CSV  que du script ^^. 
Merci pour ton temps et pour tes scripts !

On attend ça avec impatience ;)

**Comment by Angelio** [comment]
@bousmahafaycal Merci de ton retour.
Tiens moi au courant et super votre article :)

**Comment by fastclub** [comment]
Hello, j'ai deux problèmes pour ma part : 
Déja je n'arrive pas à scraper avec scraper > j'ai le message Frames are not supported at the moment. Please open the frame in a new tab or window and try scraping again. j'ai essayé les deux autres extensions et je n'y arrive pas non plus. 

ensuite j'ai un soucis avec l'installation de requirement.txt

"Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall."

help ! j'ai besoin de ce script :)

**Comment by Joemarc** [comment]
Hello @bousmahafaycal, des avancées ? :)

**Comment by bousmahafaycal** [comment]
@Joemarc @Angelio L'article a été mis à jour, cela devrait être bon actuellement. :)

**Comment by Angelio** [comment]
Toujours 😢 

`Quel message souhaitez-vous envoye : "hi"
Entrez le nom du fichier : "c.csv"
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    send_group(fbc.client, message)
  File "main.py", line 25, in send_group
    friends = fbg.get_ids__list(csv)
  File "/Users/AC/Code/PythonBot/facebook_growth/fb_group.py", line 22, in get_ids__list
    user_id = row[1]
IndexError: list index out of range`

Je vois que ton code n'a pas changé, et je pense que le problème est dans la lecture du csv. Tu as modifié des choses en local ?

et toujours ça : 😊

> Merci de ton aide et super ton code.
PS : attention dans medium F2— Envoyer un message automatiquement à toutes les personnes d’un groupe Facebook. tu as mis python main.py send_friends au lieu de python main.py send_group

**Comment by bousmahafaycal** [comment]
Hello @Angelio , mon code n'a pas changé mais la façon de scraper est censé avoir changé. As-tu refait la partie du tuto pour telecharger le fichier csv ? Il est censé avoir deux colonnes le fichier csv, premiere colonne avec nom prenom il me semble et la deuxieme est celle que tu as déjà.

Ps : Oui je viens de voir, on vient de le changer la maintenant j'ai vérifie. J'ai pas la main sur l'article en fait c'est pour ça que c'est un peu delicat. C'est pas moi qui ait fait le tuto sur scraper. Je pense que dès que j'ai un peu de temps, je vais checker pour ameliorer le code de ce script, faire en sorte qu'il ne soit plus dépendant de scraper et en faire un article moi même.

**Comment by Joemarc** [comment]
Hello @bousmahafaycal , tout marche au top merci ! :) 
J'ai juste dû spécifier `# -*- coding: utf-8 -*` au début du fichier `main.py` car il y avait des erreurs a cause des accents dans les strings

**Comment by bousmahafaycal** [comment]
Top @Joemarc ! J'ai pas vérifié pour les accents effectivement, j'utilise python 3 et je suis sur Linux, et  je n'avais pas de problème d'accents :)  Je vais l'ajouter sur le script, merci !

**Comment by Angelio** [comment]
@bousmahafaycal merci de tout ses retours alors ça marche ! 

Juste pour mon cas, je mets python main.py send_group (donc sans le 3, sinon ça ne fonctionne pas, car je suis sur le 2)

Pour le scrap, en xpath //*/div/div[2]/div/div[2]/div[1]

Merci 👍

**Comment by Joemarc** [comment]
@bousmahafaycal Au bout de 40 messages je me fais stopper par le security check de Facebook, même avec les valeurs de 45 secondes à 75 secondes d'attente entre chaque envoi => `fbchat.models.FBchatFacebookError: Error #1357007 when sending request: A security check is required to proceed.`

**Comment by karimrdy** [comment]
Merci pour tous , @bousmahafaycal peut-on utiliser le script python sans scraper pour envoyer message au groupe car je reçois la même erreur que @Angelio.

**Comment by bousmahafaycal** [comment]
C'est à dire la meme erreur que angelio ? Est-ce que tu as refais à nouveau le processus de scrap depuis le début ? @karimraoudy

**Comment by karimrdy** [comment]
@bousmahafaycal  oui j'ai suivi les étapes indiquée mais tous marche bien jusqu'a la commande send_group

**Comment by SBillion** [comment]
> Hello, j'ai deux problèmes pour ma part :
> Déja je n'arrive pas à scraper avec scraper > j'ai le message Frames are not supported at the moment. Please open the frame in a new tab or window and try scraping again. j'ai essayé les deux autres extensions et je n'y arrive pas non plus.
> 
> ensuite j'ai un soucis avec l'installation de requirement.txt
> 
> "Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall."
> 
> help ! j'ai besoin de ce script :)

@fastclub Utilise un virtualenv ou carrémment l'outil pipenv, ce sera encore plus simple. Ton problème vient du fait que tu essaies d'installer des packages dans ton environnement système et tu n'est pas utilisé le super user pour ça. De toute façon c'est vivement deconseillé, le mieux étant d'avoir un environnement cloisonné pour chaque projet python. C'est à cela que te sert pipenv. Tu fais simplement pipenv install -r requirements.txt et tout va se faire tout seul. Ensuite tu fais pipenv shell et tu es dans l'environnement cloisonné. Il ne reste plus qu'à lancer le script.

**Comment by fastclub** [comment]
Merci pour ta réponse.
le script tourne mais blocage facebook après 40 envoi. Les temps entre chaque message ont du varier. Quelqu’un sait combien de temps il faut mettre entre chaque message ?

**Comment by SBillion** [comment]
@fastclub Oui j'ai constaté le même problème et ouvert un ticket #8

**Comment by Joemarc** [comment]
C'est normal, Facebook bloque à 40-50 messages / jour aux personnes que nous ne connaissons pas

**Comment by fastclub** [comment]
d'ou tiens tu ton information @Joemarc ? as tu trouvé une parade à cette limite ? Merci pour ton retour

**Comment by Joemarc** [comment]
Car j'ai utiliser ce script pendant plusieurs semaines et que c'est écrit dans les CGU de facebook , j'ai créer 10 comptes, j'ai un peu changer les script pour que celui ci accepte diverses comptes. 
Malgré tout si vous partagez des urls, faites attention car vous pouvez vous faire blacklisté votre URL par facebook si vous la partagez de trop nombreuses fois, la technique bit.ly ne marche pas pour les plus malins non plus :)

**Comment by fastclub** [comment]
Ah d'accord, merci pour l'info. as tu une technique pour faire augmenter le taux d'acceptation des messages  ? car moi sur 40 envois j'ai peut être 3 ouvertures du messages c'est pas top....

**Comment by thomygrinta** [comment]
@fastclub comment as tu réglé le pb suivant stp: 
Déja je n'arrive pas à scraper avec scraper > j'ai le message Frames are not supported at the moment. Please open the frame in a new tab or window and try scraping again. j'ai essayé les deux autres extensions et je n'y arrive pas non plus.

Merci
