### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by Josirva** [bousmahafaycal/facebook_growth#3]
Hi bousmahafaycal,
Thank you for this great piece of code.

After following all the instructions in the tutorial "13 techniques de growth hacking expliquées step by step', I still can't get it to work. 

I keep getting the same error message:

Traceback (most recent call last):
  File "main.py", line 51, in <module>
    send_group(fbc.client, message)
  File "main.py", line 27, in send_group
    friends = fbg.get_ids__list(csv)
  File "/Desktop/facebook_growth-master/fb_group.py", line 24, in get_ids__list
    self.ids.append(int(r.group('user_id')))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by SBillion** [comment]
The pull request #5 fixed it. Wait for the merging or use the pull request

**Comment by Taifur23** [comment]
> Hi bousmahafaycal, Thank you for this great piece of code.
> 
> After following all the instructions in the tutorial "13 techniques de growth hacking expliquées step by step', I still can't get it to work.
> 
> I keep getting the same error message:
> 
> Traceback (most recent call last): File "main.py", line 51, in send_group(fbc.client, message) File "main.py", line 27, in send_group friends = fbg.get_ids__list(csv) File "/Desktop/facebook_growth-master/fb_group.py", line 24, in get_ids__list self.ids.append(int(r.group('user_id'))) AttributeError: 'NoneType' object has no attribute 'group'



> Hi bousmahafaycal, Thank you for this great piece of code.
> 
> After following all the instructions in the tutorial "13 techniques de growth hacking expliquées step by step', I still can't get it to work.
> 
> I keep getting the same error message:
> 
> Traceback (most recent call last): File "main.py", line 51, in send_group(fbc.client, message) File "main.py", line 27, in send_group friends = fbg.get_ids__list(csv) File "/Desktop/facebook_growth-master/fb_group.py", line 24, in get_ids__list self.ids.append(int(r.group('user_id'))) AttributeError: 'NoneType' object has no attribute 'group'

Hello, This is Shohag. I am a professional Ethical Hacker,
Security Specialist as well as Penetration Tester. I can test the following vulnerability and I will provide you with a perfect assessment of your website security
which makes your website safe and sound.

My Experience:
💗. Recovering Hacked WordPress Website
💗. Full Vulnerability Scan and WordPress website malware removal
💗. Vulnerability Assessment
💗. Antispam protection
💗. Analysis of database servers
💗. Restore a hacked website
💗. Ethical Hacking(White Hat Hacker)
💗. Hacked account recovery
💗. Password recovery
💗. Decode encrypted files
💗. Vulnerability Testing
💗....my WhatsApp number +8801315423936
